# Generated by Django 3.2.16 on 2022-12-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rollpost.posts'),
        ),
    ]
