# Generated by Django 3.2.16 on 2022-12-20 13:27

from django.db import migrations, models
import django.db.models.deletion
import rollpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0003_auto_20221219_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='parent',
        ),
        migrations.CreateModel(
            name='ThreadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=rollpost.models.upload_to)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollpost.posts')),
            ],
        ),
    ]
