# Generated by Django 3.2.16 on 2022-12-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0004_auto_20221220_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadpost',
            name='post_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rollpost.posts'),
        ),
    ]
