# Generated by Django 3.2.16 on 2022-12-25 23:10

from django.db import migrations, models
import rollpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0007_comment_is_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voice',
            field=models.FileField(blank=True, upload_to=rollpost.models.upload_tooo),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='voice',
            field=models.FileField(blank=True, upload_to=rollpost.models.upload_tooo),
        ),
    ]
