# Generated by Django 3.2.16 on 2022-12-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0008_auto_20221226_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
