# Generated by Django 3.2.16 on 2023-01-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0011_alter_reportadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportadmin',
            name='reportreply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rollpost.commentreply'),
        ),
    ]
