# Generated by Django 3.2.16 on 2023-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0012_reportadmin_reportreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='threadpost',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
