# Generated by Django 3.2.16 on 2023-04-26 14:08

from django.db import migrations, models
import rollpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('rollpost', '0013_auto_20230417_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to=rollpost.models.upload_to),
        ),
        migrations.AlterField(
            model_name='threadpost',
            name='image',
            field=models.ImageField(blank=True, upload_to=rollpost.models.upload_to),
        ),
    ]
