# Generated by Django 3.2.16 on 2022-12-21 05:51

from django.db import migrations, models
import rolluser.models


class Migration(migrations.Migration):

    dependencies = [
        ('rolluser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/logo.jpg', upload_to=rolluser.models.upload_to),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
