# Generated by Django 3.2.16 on 2022-12-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollchat', '0002_alter_chat_imaage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='imaage',
            field=models.TextField(blank=True),
        ),
    ]
